
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.finin.jboss.samples;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-01-21T10:28:25.755+01:00
 * Generated source version: 2.7.11
 * 
 */
public class SimpleWSS4JClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://test", "SimpleWSS4JImpl");
        QName portName = new QName("http://test", "SimpleWSS4JImplPort");

        Service service = Service.create(serviceName);
        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
                        "http://localhost:9090/SimpleWSS4JImplPort"); 
        com.finin.jboss.samples.SimpleWSS4J client = service.getPort(portName,  com.finin.jboss.samples.SimpleWSS4J.class);
        
        // Insert code to invoke methods on the client here
    }

}